# YAML
stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  before_script:
    # Ensure the local dependency is available to Maven in this job
    - test -f .libs/eodsql.jar || (echo "Missing .libs/eodsql.jar" && exit 1)
    - mvn -B -q install:install-file -Dfile=.libs/eodsql.jar -DgroupId=net.lemnik -DartifactId=eodsql -Dversion=2.2 -Dpackaging=jar
    # Optional: warm deps to speed up the package
    - mvn -B -q -DskipTests dependency:go-offline
  script:
    - mvn -B -DskipTests clean package
  artifacts:
    when: always
    paths:
      - target/
    expire_in: 1 week

test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make && rm -rf /var/lib/apt/lists/*
    - git config --global user.email "simntamjhb024@student.wethinkcode.co.za"
    - git config --global user.name "simntamjhb024"
    - mvn -B -q install:install-file -Dfile=.libs/eodsql.jar -DgroupId=net.lemnik -DartifactId=eodsql -Dversion=2.2 -Dpackaging=jar
    - mvn -B -q -DskipTests dependency:go-offline
    - rm -rf target/surefire-reports || true
  script:
    - make all-test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    expire_in: 1 week

docker-build-and-push:
  stage: deploy
  image: docker:26
  services:
    - name: docker:26-dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - docker version
    - |
      for i in $(seq 1 30); do
        if docker info >/dev/null 2>&1; then
          echo "Docker daemon is ready"; break
        fi
        echo "Waiting for Docker daemon... ($i/30)"; sleep 1
      done
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - |
      if [ -n "${CI_REGISTRY}" ]; then
        echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
        docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
        docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
        docker push "${CI_REGISTRY_IMAGE}:latest"
      fi