# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.

stages:
  - build
  - test
  - deploy
image: maven:3.9.6-eclipse-temurin-17

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn install:install-file -Dfile=.libs/eodsql.jar -DgroupId=net.lemnik -DartifactId=eodsql -Dversion=2.2 -Dpackaging=jar
    - mvn package -DskipTests
    - echo "Compile complete."

test-iretation2-job:
  stage: test
#  image: maven:3.9.6-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y make
    - git config --global user.email "remosehjhb024@student.wethinkcode.co.za"
    - git config --global user.name "Reitumetse Marline Mosehla"
  script:
    - echo "Running unit tests..."
    - make test-iteration-2
    - echo "Unit tests complete."

test-our-server-job:
  stage: test
#  image: maven:3.9.6-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y make
    - git config --global user.email "remosehjhb024@student.wethinkcode.co.za"
    - git config --global user.name "Reitumetse Marline Mosehla"
  script:
    - echo "Running unit tests..."
    - make test-our-server
    - echo "Unit tests complete."

test-saveWorld-job:
  stage: test
#  image: maven:3.9.6-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y make
    - git config --global user.email "remosehjhb024@student.wethinkcode.co.za"
    - git config --global user.name "Reitumetse Marline Mosehla"
  script:
    - echo "Running unit tests..."
    - make test-iteration-3
    - echo "Unit tests complete."

docker-build:
  stage: deploy
  image: docker:stable

  services:
    - docker:dind
  variables:
    CI_REGISTRY: gitlab.wethinkco.de:5050
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build-job
  environment: production
  script:
    - echo "Logging in to docker registry"
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username "$CI_REGISTRY_USER" --password-stdin
    - docker build -t gitlab.wethinkco.de:5050/mmntshajhb024/brownfields_robot_worlds_1 .
    - docker push gitlab.wethinkco.de:5050/mmntshajhb024/brownfields_robot_worlds_1
    - echo "Application successfully deployed"