# YAML
docker-build:
  stage: docker
  image: docker:26
  services:
    - name: docker:26-dind
      command: ["--tls=false"]   # disable TLS in DinD
  variables:
    DOCKER_TLS_CERTDIR: ""       # disable TLS in client
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    # Optional: show versions to help debug if needed
    - docker version
    # Wait for Docker daemon to be ready (DinD can take a few seconds)
    - |
      for i in $(seq 1 30); do
        if docker info >/dev/null 2>&1; then
          echo "Docker daemon is ready"; break
        fi
        echo "Waiting for Docker daemon... ($i/30)"; sleep 1
      done
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    # Optional push
    - |
      if [ -n "${CI_REGISTRY}" ]; then
        echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
        docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
        docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
        docker push "${CI_REGISTRY_IMAGE}:latest"
      fi