# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.

stages:
  - build
  - test
  - docker

variables:
  DOCKER_IMAGE: gitlab.wethinkco.de:5050/mmntshajhb024/brownfields_robot_worlds_1:1.0.0

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Compiling the code..."
    - mvn package -DskipTests
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  before_script:
    - apt-get update && apt-get install -y make
    - git config --global user.email "remosehjhb024@student.wethinkcode.co.za"
    - git config --global user.name "Reitumetse Marline Mosehla"
  script:
    - echo "Running unit tests..."
    - make test-iteration-2
    - make test-our-server
    - echo "Unit tests complete."

docker-build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$REGISTRY_TOKEN" | docker login gitlab.wethinkco.de:5050 -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker save $DOCKER_IMAGE > image.tar
    - docker push $DOCKER_IMAGE
  artifacts:
    paths:
      - image.tar
    expire_in: 1 week
  only:
    - main