_version = 0.1

[brownfields_robot_worlds_1]
activity_id = "brn-ex-iteration-4"

[team]
members = [
    "mmntshajhb024@student.wethinkcode.co.za",
    "simntamjhb024@student.wethinkcode.co.za",
    "remosehjhb024@student.wethinkcode.co.za",
    "mochoenjhb024@student.wethinkcode.co.za"
]